"""Hand-checked utility tags. Crypto entries REPLACE category-derived tags for
that symbol (categories are noisy for the largest coins); stocks are all here."""

CRYPTO_EXTRA_LABELS = {
    "money": "Money / store of value",
    "legacy": "No current function: its chain was shut down",
}

CRYPTO = {
    "BTC": ["money", "payments", "mining"], "ETH": ["gas", "staking", "money"], "SOL": ["gas", "staking"],
    "XRP": ["payments", "gas"], "BNB": ["exchange", "gas", "staking"], "DOGE": ["meme", "payments", "mining"],
    "ADA": ["gas", "staking", "governance"], "TRX": ["gas", "payments", "staking"], "XLM": ["payments", "gas"],
    "HBAR": ["gas", "staking"], "HYPE": ["derivatives", "gas", "staking"], "ARB": ["scaling", "governance"],
    "LTC": ["money", "payments", "mining"], "BCH": ["payments", "mining"], "LINK": ["oracle", "interop", "staking"],
    "AVAX": ["gas", "staking"], "DOT": ["staking", "interop", "governance"], "TON": ["gas", "payments", "staking"],
    "SUI": ["gas", "staking"], "NEAR": ["gas", "staking"], "XMR": ["privacy", "money", "mining"],
    "ZEC": ["privacy", "money", "mining"], "UNI": ["dex", "governance"], "AAVE": ["lending", "governance"],
    "ATOM": ["staking", "interop"], "ETC": ["gas", "mining"], "FIL": ["depin", "gas"], "ICP": ["gas", "staking"],
    "OP": ["scaling", "governance"], "POL": ["scaling", "gas", "staking"], "APT": ["gas", "staking"],
    "RENDER": ["depin", "ai"], "TAO": ["ai", "staking"], "FET": ["ai"], "INJ": ["derivatives", "gas", "staking"],
    "SEI": ["gas", "staking"], "TIA": ["scaling", "staking"], "LDO": ["liquid-staking", "governance"],
    "ENA": ["yield", "governance"], "ONDO": ["rwa", "governance"], "PEPE": ["meme"], "SHIB": ["meme"],
    "WIF": ["meme"], "BONK": ["meme"], "FLOKI": ["meme"], "PENGU": ["meme", "nft"], "TRUMP": ["meme"],
    "SKY": ["stablecoin", "lending", "governance"], "MKR": ["stablecoin", "lending", "governance"],
    "CRV": ["dex", "governance"], "PENDLE": ["yield"], "JUP": ["dex", "governance"], "RAY": ["dex"],
    "CAKE": ["dex"], "GMX": ["derivatives", "governance"], "DYDX": ["derivatives", "governance"],
    "WLD": ["social"], "GRT": ["oracle"], "PYTH": ["oracle"], "QNT": ["interop", "infra"], "VET": ["gas"],
    "ALGO": ["gas", "staking"], "STX": ["scaling", "gas"], "KAS": ["mining", "payments"],
    "EIGEN": ["liquid-staking", "staking"], "ETHFI": ["liquid-staking"], "JTO": ["liquid-staking", "governance"],
    "ZRO": ["interop"], "W": ["interop"], "AR": ["depin"], "HNT": ["depin"], "IO": ["depin", "ai"],
    "VIRTUAL": ["ai"], "SAND": ["gaming", "nft"], "MANA": ["gaming", "nft"], "AXS": ["gaming"], "GALA": ["gaming"],
    "IMX": ["scaling", "gaming", "nft"], "APE": ["governance", "nft"], "ENS": ["social", "governance"],
    "CRO": ["exchange", "gas"], "OKB": ["exchange"], "LEO": ["exchange"], "GT": ["exchange"], "KCS": ["exchange"],
    "TWT": ["infra"], "SNX": ["derivatives"], "COMP": ["lending", "governance"],
    "MOVR": ["legacy"], "GLMR": ["legacy"],
    "WLFI": ["governance", "stablecoin"], "XTZ": ["gas", "staking", "governance"], "EGLD": ["gas", "staking"],
    "NEO": ["gas"], "IOTA": ["gas", "depin"], "THETA": ["depin", "gas"], "CHZ": ["social", "gas"],
    "1INCH": ["dex"], "SUN": ["dex"], "JST": ["lending"], "FLOW": ["gas", "nft"], "KAIA": ["gas"],
    "MINA": ["gas", "scaling"], "ZK": ["scaling"], "STRK": ["scaling"], "ASTER": ["derivatives"],
    "PUMP": ["exchange", "meme"], "MNT": ["scaling", "governance"], "FF": ["yield", "governance"], "USD1": ["stablecoin"], "XPL": ["gas", "payments"], "PAXG": ["rwa"],
}

STOCK_LABELS = {
    "consumer-hw": "Consumer devices", "cloud": "Cloud computing", "software": "Business software", "ai": "AI",
    "chips": "Chips", "chip-equipment": "Chipmaking equipment", "networking": "Networking", "hardware": "Servers and storage",
    "ads": "Online advertising", "ecommerce": "E-commerce", "streaming": "Streaming and media", "video-games": "Video games",
    "social": "Social media", "security": "Cybersecurity", "data": "Data and analytics", "payments": "Payments",
    "banking": "Banking", "investment-banking": "Investment banking", "asset-mgmt": "Asset management", "brokerage": "Brokerage",
    "markets-data": "Exchanges, ratings and market data", "insurance": "Insurance", "lending": "Consumer lending",
    "oil-gas": "Oil and gas production", "refining": "Refining", "oilfield-services": "Oilfield services",
    "pipelines": "Pipelines and LNG", "power-utility": "Power utility", "solar": "Solar", "nuclear": "Nuclear power",
    "grid-equipment": "Power and grid equipment", "machinery": "Industrial machinery", "aerospace-defense": "Aerospace and defense",
    "rail": "Rail freight", "logistics": "Shipping and logistics", "autos": "Autos", "evs": "Electric vehicles",
    "auto-parts": "Auto parts", "pharma": "Pharma", "biotech": "Biotech", "gene-editing": "Gene editing",
    "medtech": "Medical devices", "health-insurance": "Health insurance", "health-services": "Health services and distribution",
    "lab-tools": "Lab tools and diagnostics", "animal-health": "Animal health", "retail": "Retail", "restaurants": "Restaurants",
    "staples": "Household staples, food and drink", "apparel": "Apparel and beauty", "home-improvement": "Home improvement",
    "travel": "Travel and lodging", "airlines": "Airlines", "cruises": "Cruise lines", "telecom": "Telecom",
    "chemicals": "Chemicals and industrial gases", "metals-mining": "Metals and mining", "gold": "Gold", "steel": "Steel",
    "battery-materials": "Lithium and rare earths", "reit": "Real estate (REIT)", "data-centers": "Data centers",
    "towers": "Cell towers", "crypto": "Crypto exposure", "delivery": "Rides and delivery", "quantum": "Quantum computing",
    "space": "Space", "evtol": "Air taxis (eVTOL)", "waste": "Waste and environmental", "rental": "Equipment rental",
    "construction": "Engineering and construction",
}

STOCK = {
    "AAPL": ["consumer-hw", "software"], "MSFT": ["cloud", "software", "ai"], "NVDA": ["chips", "ai"],
    "GOOGL": ["ads", "cloud", "ai"], "AMZN": ["ecommerce", "cloud"], "META": ["social", "ads", "ai"], "TSLA": ["evs", "solar", "ai"],
    "AVGO": ["chips", "networking", "software"],
    "JPM": ["banking", "investment-banking"], "GS": ["investment-banking", "asset-mgmt"], "MS": ["investment-banking", "brokerage", "asset-mgmt"],
    "BAC": ["banking"], "WFC": ["banking"], "C": ["banking", "investment-banking"], "V": ["payments"], "MA": ["payments"],
    "BLK": ["asset-mgmt"], "SCHW": ["brokerage", "banking"], "AXP": ["payments", "lending"], "COF": ["banking", "lending"],
    "PNC": ["banking"], "USB": ["banking"], "TFC": ["banking"], "STT": ["asset-mgmt", "banking"],
    "SPGI": ["markets-data"], "MCO": ["markets-data"], "ICE": ["markets-data"], "CME": ["markets-data"], "NDAQ": ["markets-data"],
    "AIG": ["insurance"], "MET": ["insurance"], "PRU": ["insurance", "asset-mgmt"], "TRV": ["insurance"], "ALL": ["insurance"],
    "PGR": ["insurance"], "CB": ["insurance"], "AON": ["insurance"],
    "XOM": ["oil-gas", "refining", "chemicals"], "CVX": ["oil-gas", "refining"], "COP": ["oil-gas"], "MPC": ["refining"],
    "VLO": ["refining"], "PBF": ["refining"], "DINO": ["refining"], "SLB": ["oilfield-services"], "HAL": ["oilfield-services"],
    "BKR": ["oilfield-services", "grid-equipment"], "OXY": ["oil-gas", "chemicals"], "DVN": ["oil-gas"], "FANG": ["oil-gas"],
    "EOG": ["oil-gas"], "PSX": ["refining", "pipelines"], "KMI": ["pipelines"], "WMB": ["pipelines"], "OKE": ["pipelines"], "LNG": ["pipelines"],
    "FSLR": ["solar"], "ENPH": ["solar"], "RUN": ["solar"], "NEE": ["power-utility", "solar"], "DUK": ["power-utility", "nuclear"],
    "SO": ["power-utility", "nuclear"], "AEP": ["power-utility"], "D": ["power-utility", "nuclear"], "EXC": ["power-utility"], "SRE": ["power-utility", "pipelines"],
    "GE": ["aerospace-defense"], "BA": ["aerospace-defense"], "CAT": ["machinery"], "DE": ["machinery"], "LMT": ["aerospace-defense", "space"],
    "RTX": ["aerospace-defense"], "HON": ["machinery", "aerospace-defense"], "MMM": ["machinery"], "EMR": ["machinery"],
    "ETN": ["grid-equipment"], "PH": ["machinery", "aerospace-defense"], "ITW": ["machinery"], "CSX": ["rail"], "UNP": ["rail"],
    "NSC": ["rail"], "FDX": ["logistics"], "UPS": ["logistics"], "WM": ["waste"], "URI": ["rental"], "PWR": ["construction", "grid-equipment"],
    "GEV": ["grid-equipment", "nuclear"], "VRT": ["grid-equipment", "data-centers"], "ROK": ["machinery"], "DOV": ["machinery"],
    "CMI": ["machinery", "grid-equipment"], "PCAR": ["autos"],
    "TSM": ["chips"], "ASML": ["chip-equipment"], "AMD": ["chips", "ai"], "MU": ["chips"], "INTC": ["chips"], "QCOM": ["chips"],
    "TXN": ["chips"], "AMAT": ["chip-equipment"], "LRCX": ["chip-equipment"], "KLAC": ["chip-equipment"], "ADI": ["chips"],
    "NXPI": ["chips"], "ON": ["chips"], "MRVL": ["chips", "networking"], "ARM": ["chips"], "TER": ["chip-equipment"],
    "MCHP": ["chips"], "SWKS": ["chips"], "QRVO": ["chips"],
    "DELL": ["hardware"], "SMCI": ["hardware", "ai"], "WDC": ["hardware"], "ANET": ["networking"], "CSCO": ["networking", "security"],
    "GLW": ["hardware", "networking"], "HPQ": ["consumer-hw"], "HPE": ["hardware", "networking"], "CIEN": ["networking"],
    "NFLX": ["streaming"], "DIS": ["streaming", "travel"], "ORCL": ["cloud", "software"], "IBM": ["software", "cloud", "quantum"],
    "CRM": ["software", "ai"], "NOW": ["software", "ai"], "PLTR": ["software", "data", "ai"], "ADBE": ["software"], "SAP": ["software"],
    "INTU": ["software"], "ADSK": ["software"], "WDAY": ["software"], "TEAM": ["software"], "HUBS": ["software"], "GTLB": ["software"],
    "MDB": ["software", "data"], "OKTA": ["security"], "TWLO": ["software"], "DOCU": ["software"], "ZM": ["software"],
    "TTD": ["ads"], "APP": ["ads", "video-games"], "TTWO": ["video-games"], "RBLX": ["video-games"], "PINS": ["social", "ads"],
    "SPOT": ["streaming"], "ROKU": ["streaming", "ads"], "WBD": ["streaming"], "CMCSA": ["telecom", "streaming"],
    "CRWD": ["security"], "PANW": ["security"], "ZS": ["security"], "DDOG": ["software", "data"], "SNOW": ["data", "cloud"],
    "NET": ["security", "cloud"], "FTNT": ["security"], "TENB": ["security"], "RPD": ["security"], "QLYS": ["security"], "ESTC": ["data", "security"],
    "UNH": ["health-insurance", "health-services"], "LLY": ["pharma"], "JNJ": ["pharma", "medtech"], "ISRG": ["medtech"],
    "PFE": ["pharma"], "MRK": ["pharma", "animal-health"], "ABBV": ["pharma"], "AMGN": ["biotech"], "GILD": ["biotech"],
    "BMY": ["pharma"], "VRTX": ["biotech"], "REGN": ["biotech"], "MRNA": ["biotech"], "BIIB": ["biotech"], "ZTS": ["animal-health"],
    "TMO": ["lab-tools"], "DHR": ["lab-tools"], "ABT": ["medtech", "lab-tools"], "MDT": ["medtech"], "SYK": ["medtech"],
    "BSX": ["medtech"], "CI": ["health-insurance", "health-services"], "CVS": ["health-services", "health-insurance", "retail"],
    "HUM": ["health-insurance"], "ELV": ["health-insurance"], "MCK": ["health-services"], "HCA": ["health-services"],
    "CRSP": ["gene-editing", "biotech"], "NTLA": ["gene-editing", "biotech"], "TEM": ["ai", "lab-tools"],
    "COST": ["retail"], "WMT": ["retail", "ecommerce"], "TGT": ["retail"], "HD": ["home-improvement"], "LOW": ["home-improvement"],
    "NKE": ["apparel"], "SBUX": ["restaurants"], "MCD": ["restaurants"], "CMG": ["restaurants"], "YUM": ["restaurants"],
    "KO": ["staples"], "PEP": ["staples"], "PG": ["staples"], "CL": ["staples"], "KMB": ["staples"], "MDLZ": ["staples"],
    "GIS": ["staples"], "KHC": ["staples"], "EL": ["apparel"], "LULU": ["apparel"], "ROST": ["retail"], "TJX": ["retail"],
    "ORLY": ["auto-parts", "retail"], "AZO": ["auto-parts", "retail"],
    "ABNB": ["travel"], "BKNG": ["travel"], "MAR": ["travel"], "HLT": ["travel"], "RCL": ["cruises"], "CCL": ["cruises"],
    "NCLH": ["cruises"], "DAL": ["airlines"], "UAL": ["airlines"], "AAL": ["airlines"], "LUV": ["airlines"],
    "F": ["autos", "evs"], "GM": ["autos", "evs"], "RIVN": ["evs"], "LCID": ["evs"], "NIO": ["evs"], "LI": ["evs"], "XPEV": ["evs"],
    "HMC": ["autos"], "TM": ["autos"], "APTV": ["auto-parts"], "BWA": ["auto-parts"],
    "T": ["telecom"], "VZ": ["telecom"], "TMUS": ["telecom"],
    "LIN": ["chemicals"], "APD": ["chemicals"], "SHW": ["chemicals"], "FCX": ["metals-mining", "gold"], "NEM": ["gold"],
    "NUE": ["steel"], "STLD": ["steel"], "CLF": ["steel"], "AA": ["metals-mining"], "DOW": ["chemicals"], "DD": ["chemicals"],
    "ALB": ["battery-materials", "chemicals"], "MP": ["battery-materials"],
    "AMT": ["reit", "towers"], "PLD": ["reit", "logistics"], "EQIX": ["reit", "data-centers"], "SPG": ["reit", "retail"],
    "O": ["reit", "retail"], "CCI": ["reit", "towers"], "PSA": ["reit"], "DLR": ["reit", "data-centers"], "WELL": ["reit", "health-services"],
    "COIN": ["crypto", "markets-data"], "HOOD": ["brokerage", "crypto"], "MSTR": ["crypto", "software"], "DASH": ["delivery"],
    "UBER": ["delivery"], "SNAP": ["social", "ads"], "SHOP": ["ecommerce", "software"], "PYPL": ["payments"],
    "SOFI": ["banking", "lending"], "AFRM": ["lending", "payments"], "UPST": ["lending", "ai"], "TOST": ["payments", "software"],
    "NU": ["banking", "lending"], "RDDT": ["social", "ads"],
    "BABA": ["ecommerce", "cloud"], "JD": ["ecommerce"], "PDD": ["ecommerce"], "SE": ["ecommerce", "video-games", "payments"],
    "MELI": ["ecommerce", "payments"], "GRAB": ["delivery", "payments"],
    "IONQ": ["quantum"], "RGTI": ["quantum"], "OKLO": ["nuclear"], "SMR": ["nuclear"], "JOBY": ["evtol"], "ACHR": ["evtol"],
    "ASTS": ["space", "telecom"], "RKLB": ["space"], "LUNR": ["space"],
}
