"""Writes signals-worker/utility-tags.js: what each asset on the signals page is used for.

Crypto: CoinGecko category membership mapped through taxonomy.UTILITY, keyed by
CoinGecko id (a ticker can be shared by unrelated coins), with hand-checked
tags (curated.CRYPTO) replacing the derived ones for the largest coins.
Stocks: hand-checked business lines (curated.STOCK).

usage: python3 gen_utility_tags.py <out.js> <markets.json>
"""
import json, os, sys, datetime
from taxonomy import UTILITY
from curated import CRYPTO, CRYPTO_EXTRA_LABELS, STOCK, STOCK_LABELS
from panel import PRIORITY

HERE = os.path.dirname(os.path.abspath(__file__))
out_path, markets_path = sys.argv[1], sys.argv[2]

SHORT = {
    "gas": "Network fees", "scaling": "Scaling", "staking": "Staking", "mining": "Mined (PoW)", "payments": "Payments",
    "stablecoin": "Stablecoin", "exchange": "Exchange token", "dex": "DEX trading", "lending": "Lending",
    "derivatives": "Derivatives", "prediction": "Prediction / betting", "liquid-staking": "Liquid staking", "yield": "Yield",
    "oracle": "Oracle / data", "interop": "Cross-chain", "privacy": "Privacy", "ai": "AI", "depin": "DePIN",
    "rwa": "Real-world assets", "gaming": "Gaming", "nft": "NFTs", "social": "Social / identity", "infra": "Dev infrastructure",
    "governance": "Governance", "meme": "Meme", "money": "Store of value", "legacy": "Legacy: chain shut down",
}
LONG = {**{k: v[0] for k, v in UTILITY.items()}, **CRYPTO_EXTRA_LABELS}
LONG["legacy"] = "No current function: its own chain was shut down and it now trades as a plain token"
assert set(SHORT) == set(LONG), set(SHORT) ^ set(LONG)

def clean(tags):
    """Category-derived tags, tidied: CoinGecko files DEX and perp tokens under
    'exchange-based tokens' and Trump-linked stablecoins under meme themes."""
    t = set(tags)
    if "stablecoin" in t: t.discard("meme")
    if t & {"dex", "derivatives"}: t.discard("exchange")
    return sorted(t, key=PRIORITY.index)[:3]

mk = json.load(open(markets_path))
by_id = {}
for tag, (_, cats) in UTILITY.items():
    for c in cats:
        p = os.path.join(HERE, "mem", c + ".json")
        if os.path.exists(p):
            for r in json.load(open(p)): by_id.setdefault(r["id"], set()).add(tag)
crypto = {}
seen_symbol = set()
for m in mk:                                   # market-cap order: the largest coin owns a curated ticker
    s, cid = m["symbol"].upper(), m["id"]
    if s in CRYPTO and s not in seen_symbol:
        crypto[cid] = CRYPTO[s]
    elif cid in by_id:
        crypto[cid] = clean(by_id[cid])
    seen_symbol.add(s)
missing_curated = [s for s in CRYPTO if s not in {m["symbol"].upper() for m in mk}]

as_of = datetime.date.today().isoformat()
js = f"""// What each asset on the signals page is used for (user-requested 2026-10-01:
// "find and tag assets/coins on fcs signals page with their utility (what they
// are used for. could be multiple)"). GENERATED by
// docs/research-2026-10-01-categories/scripts/gen_utility_tags.py; edit the
// curated lists there and regenerate rather than editing this file.
//
// Crypto: CoinGecko category membership (as of {as_of}) mapped to plain uses,
// keyed by CoinGecko id because a ticker can belong to several unrelated coins.
// The largest coins carry hand-checked tags instead. Stocks: hand-checked
// business lines. Informational only: never an input to any score.
export const UTILITY_TAGS_AS_OF = '{as_of}';
export const UTILITY_LABELS = {json.dumps({k: [SHORT[k], LONG[k]] for k in PRIORITY if k in SHORT}, indent=0)};
export const STOCK_LABELS = {json.dumps(STOCK_LABELS, indent=0)};
export const CRYPTO_UTILITY = {json.dumps(crypto, separators=(',', ':'))};
export const STOCK_UTILITY = {json.dumps(STOCK, separators=(',', ':'))};

// [{{ id, label, title }}] for one asset. A crypto row carries its CoinGecko id;
// a stock row has none, which is also what keeps a ticker shared by a stock and
// a coin from borrowing the other's tags.
export function utilityTagsFor(symbol, coingeckoId) {{
  if (coingeckoId) {{
    return (CRYPTO_UTILITY[coingeckoId] || []).map((id) => ({{ id, label: UTILITY_LABELS[id][0], title: UTILITY_LABELS[id][1] }}));
  }}
  return (STOCK_UTILITY[String(symbol || '').toUpperCase()] || []).map((id) => ({{ id, label: STOCK_LABELS[id], title: STOCK_LABELS[id] }}));
}}
"""
open(out_path, "w").write(js)
print(f"wrote {out_path}: {len(crypto)} coins tagged ({sum(1 for c in crypto if c)}), {len(STOCK)} stocks; curated tickers not in markets: {missing_curated}")
